/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in a normal project setup and kept here so
// type checking has the expected ambient declarations from the first scaffold.
